version: '3.9'

services:
  mysql:
    container_name: 'todo-app-mysql'
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./create-local-db:/docker-entrypoint-initdb.d
    networks:
      - todo-app
    ports:
      - 3306:3306

  backend:
    container_name: 'todo-app-backend'
    image: 'tarkanaciksoz/todo-app-backend:latest'
    build:
      context: .
      args:
        - ENV=${APP_ENV}
    restart: unless-stopped
    environment:
      ENV: ${APP_ENV}
    networks:
      - todo-app
    ports:
      - 9090:9090
  
  frontend:
    container_name: todo-app-frontend
    image: tarkanaciksoz/todo-app-frontend:latest
    build:
      context: frontend
      args:
        - ENV=${APP_ENV}
    restart: unless-stopped
    environment:
      ENV: ${APP_ENV}
    healthcheck:
      test: curl --fail ${APP_URL} || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - todo-app
    ports:
      - 80:80

networks:
  todo-app:
    name: todo-app
    driver: bridge