
name: Deploy To Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Docker Compose down
        run: make destroy

      - name: Docker system prune
        run: docker system prune -f
        
      - name: Docker Compose build and up
        run: make build-test
