
name: Deploy To Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    services:
      mysql:
        container_name: todo-app-mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_NAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
        healthcheck:
          test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
          interval: 2s
          timeout: 20s
          retries: 10
        volumes:
          - ../.././docker/create-local-db:/docker-entrypoint-initdb.d
        networks:
          - todo-app
        ports:
          - 3306:3306

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go

    - name: Checkout to app dir
      uses: actions/checkout@v2

    - name: Test For backend
      run: CGO_ENABLED=0 APP_ENV=test go test --tags test ./...