
name: Deploy To Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Docker system prune
        run: docker system prune -f

      - name: Docker Compose down
        run: cd ../../ && make destroy

      - name: Docker Compose build and up
        run: cd ../../ && make build-test
